[PHP]
extension_dir = "C:\php\ext"
extension=curl
extension=gd
extension=mbstring
extension=mysqli
extension=pdo_mysql
extension=openssl
extension=fileinfo
extension=zip
extension=pdo_sqlite
extension=sqlite3
date.timezone = Asia/Shanghai
display_errors = On
error_reporting = E_ALL
